#!/usr/bin/env python

import sys, os, random, time

def usage():
    print 'usage:', os.path.basename(sys.argv[0]) + ' <low> <hi>'
    sys.exit(1)

def main():
    if ((len(sys.argv)-1) != 2):
        usage()
    l = int(sys.argv[1])
    h = int(sys.argv[2])
    diff = h - l + 1
    t = time.time()
    t = t - int(t)
    t = t * 1000000
    random.seed(t)
    print int(random.random() * diff) + l

if __name__ == "__main__": # when run as a script
    main()
