#!/usr/bin/env python
import sys, os, re

def usage():
    s = 'usage: ' + os.path.basename(sys.argv[0]) + ' [--nolib]\n'
    sys.stderr.write(s)
    sys.exit(1)

nolib=0
while len(sys.argv)-1 > 0:
    if sys.argv[1]=="--nolib":
        nolib=1
        sys.argv = sys.argv[:1] + sys.argv[2:]
    else:
        usage()

if ((len(sys.argv)-1) != 0):
    usage()

def is_csh():
    csh = """/bin/tcsh$ /bin/csh$""".split()
    myshell = os.getenv('SHELL')
    for shell in csh:
        if re.search(shell, myshell):
            return True
    return False

bindir = os.path.dirname(os.path.realpath(sys.argv[0]))
if os.path.basename(bindir) == 'src':
    libdir = bindir
else:
    libdir = os.path.join(os.path.dirname(bindir), 'lib')

if not is_csh():
    print 'PATH=%s:$PATH\nexport PATH' % (bindir)
    if not nolib:
        print 'LD_LIBRARY_PATH=%s:$LD_LIBRARY_PATH\nexport LD_LIBRARY_PATH' % (libdir)
else:
    print """if ( $?PATH ) then
    setenv PATH %s:$PATH
else
    setenv PATH %s
endif""" % (bindir, bindir)
    if not nolib:
        print """if ( $?LD_LIBRARY_PATH ) then
    setenv LD_LIBRARY_PATH %s:$LD_LIBRARY_PATH
else
    setenv LD_LIBRARY_PATH %s
endif""" % (libdir, libdir)
